# Site settings
title: PharmCAT
email: pharmcat@pharmgkb.org
description: >- # this means to ignore newlines until next YAML key
  The Pharmacogenomics Clinical Annotation Tool (PharmCAT) is an open-source tool that takes an individualâ€™s genetic
  data and determines their respective drug-related genotypes and phenotypes. PharmCAT produces a personalized report
  with genotype-specific expert-reviewed drug prescribing recommendations.
twitter_username: pharmgkb
github_username:  pharmgkb

# Build settings
plugins:
  - jemoji
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "home"
kramdown:
  smart_quotes: [ "apos", "apos", "quot", "quot" ]
  typographic_symbols:
    mdash: "---"
    ndash: "--"

# Just-the-Docs settings
color_scheme: pharmcat
ga_tracking: G-7ZP1HHBWTE
ga_tracking_anonymize_ip: true
logo: /images/pharmcat_header.png
show_downloads: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - Makefile
  - Dockerfile
